# Setup
title:        Android Dev
tagline:      Цикл статей про разработку под Android
baseurl:      "http://tepikin.github.io"
paginate:     1
excerpt_separator: <!--more-->

# About/contact
author:
  name:       Тепикин Егор 
  url:        https://github.com/tepikin

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown